name: batchcp
channels:
  - bioconda
  - conda-forge
dependencies:
  - anndata2ri=1.1
  - anndata=0.10.3
  - chex=0.1.81
  - deprecated=1.2.14
  - kneed=0.8.5
  - leidenalg=0.9.1
  - llvmlite=0.41.1
  - louvain=0.8.0
  - numba=0.58.1
  - numpy=1.26.2
  - pandas=2.1.3
  - pillow=9.4.0
  - pip=23.3.1
  - plotly=5.18.0
  - pyarrow=11.0.0
  - pydot=1.4.2
  - pymde=0.1.18
  - pynndescent=0.5.11
  - python-kaleido=0.2.1
  - r-devtools=2.4.5
  - rpy2=3.5.11
  - scanpy=1.9.5
  - scikit-learn=1.3.2
  - scikit-misc=0.1.4
  - scvi-tools=0.20.3
  - snakemake=7.32.4
  - umap-learn=0.5.5
  - pip:
      - desc==2.1.1
      - harmonypy==0.0.9
      - python-igraph==0.10.4
      - scanorama==1.7.3
      - sqlalchemy==1.4.46
      - git+https://github.com/cytomining/copairs.git@v0.3.3
      - git+https://github.com/cytomining/pycytominer.git@b2c6cc4
