name: batchcp
channels:
  - bioconda
  - conda-forge
dependencies:
  - r-devtools=2.4.5
  - numpy=1.23.5
  - pandas=1.5.3
  - scvi-tools=0.20.2
  - chex=0.1.6
  - tensorflow=2.11.0
  - tensorflow-probability=0.19.0
  - pyarrow=11.0.0
  - plotly=5.13.1
  - scikit-learn=1.2.2
  - scikit-misc=0.1.4
  - leidenalg=0.9.1
  - umap-learn=0.5.3
  - numba=0.56.4
  - anndata=0.8.0
  - scanpy=1.9.3
  - deprecated=1.2.13
  - llvmlite=0.39.1
  - louvain=0.8.0
  - pip=23.0.1
  - pillow=9.4.0
  - pydot=1.4.2
  - kneed=0.7.0
  - rpy2=3.5.10
  - pymde=0.1.18
  - python-kaleido=0.2.1
  - anndata2ri=1.1
  - pip:
      - sqlalchemy==1.4.46
      - python-igraph==0.10.4
      - harmonypy==0.0.9
      - scanorama==1.7.3
      - desc==2.1.1
      - git+https://github.com/cytomining/copairs.git@v0.0.3
      - git+https://github.com/cytomining/pycytominer.git@b2c6cc4
